version: "3.8"
services:
  jenkins:
    build: .
    container_name: jenkins
    restart: always
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins-data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock
    user: "0:999"  # root user with docker group id
    group_add:
      - "999"  # docker group id to ensure jenkins user has docker access
    command: >
      bash -c "chgrp docker /var/run/docker.sock && chmod 666 /var/run/docker.sock && exec /bin/tini -- /usr/local/bin/jenkins.sh"

volumes:
  jenkins-data:

